import { mkdir, writeFile } from "node:fs/promises";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { WorkspaceModel } from "@exo/core";
import type { AgentInstructionOverlay } from "../shared/api";

type AgentInstructionOverlayDraft = AgentInstructionOverlay & {
  targetRootPath: string;
};

export function agentInstructionOverlays(workspaceModel: WorkspaceModel): AgentInstructionOverlay[] {
  return agentInstructionOverlayDrafts(workspaceModel).map(({ targetRootPath: _targetRootPath, ...overlay }) => overlay);
}

function agentInstructionOverlayDrafts(workspaceModel: WorkspaceModel): AgentInstructionOverlayDraft[] {
  const overlayRoots = [
    {
      id: "global",
      scope: "global" as const,
      label: "Global runtime overlay",
      path: path.join(workspaceModel.workspaceRoot, ".exo", "instructions", "global.md"),
      targetRootPath: workspaceModel.workspaceRoot,
    },
    ...workspaceModel.noteRoots.map((root) => ({
      id: `notes:${root.path}`,
      scope: "notes" as const,
      label: `${root.label} runtime overlay`,
      path: path.join(workspaceModel.workspaceRoot, ".exo", "instructions", "notes", `${overlayFileStem(root.label, root.path)}.md`),
      targetRootPath: root.path,
    })),
    ...workspaceModel.projectRoots.map((root) => ({
      id: `project:${root.path}`,
      scope: "project" as const,
      label: `${root.label} runtime overlay`,
      path: path.join(workspaceModel.workspaceRoot, ".exo", "instructions", "projects", `${overlayFileStem(root.label, root.path)}.md`),
      targetRootPath: root.path,
    })),
  ];

  return overlayRoots.map((overlay) => ({
    id: overlay.id,
    scope: overlay.scope,
    label: overlay.label,
    path: overlay.path,
    targetRootPath: overlay.targetRootPath,
    body: renderAgentInstructionOverlay(workspaceModel, overlay.label, overlay.scope, overlay.targetRootPath),
  }));
}

export async function writeAgentInstructionOverlays(workspaceModel: WorkspaceModel): Promise<AgentInstructionOverlay[]> {
  const overlays = agentInstructionOverlays(workspaceModel);
  await Promise.all(overlays.map(async (overlay) => {
    await mkdir(path.dirname(overlay.path), { recursive: true });
    await writeFile(overlay.path, overlay.body, "utf8");
  }));
  return overlays;
}

export function writeAgentInstructionOverlaysSync(workspaceModel: WorkspaceModel): AgentInstructionOverlay[] {
  const overlays = agentInstructionOverlays(workspaceModel);
  for (const overlay of overlays) {
    mkdirSync(path.dirname(overlay.path), { recursive: true });
    writeFileSync(overlay.path, overlay.body, "utf8");
  }
  return overlays;
}

export function agentInstructionOverlayEnv(workspaceModel: WorkspaceModel, cwd: string): Record<string, string> {
  const overlay = resolveAgentInstructionOverlay(workspaceModel, cwd);
  return {
    EXO_INSTRUCTIONS: overlay.path,
    EXO_INSTRUCTIONS_SCOPE: overlay.scope,
    EXO_INSTRUCTIONS_LABEL: overlay.label,
  };
}

export function resolveAgentInstructionOverlay(workspaceModel: WorkspaceModel, cwd: string): AgentInstructionOverlay {
  const overlays = agentInstructionOverlayDrafts(workspaceModel);
  const roots = [
    ...workspaceModel.projectRoots.map((root) => ({ scope: "project" as const, path: root.path })),
    ...workspaceModel.noteRoots.map((root) => ({ scope: "notes" as const, path: root.path })),
  ]
    .filter((root) => isPathWithin(root.path, cwd))
    .sort((left, right) => right.path.length - left.path.length);

  const matchedRoot = roots[0];
  const byTargetRoot = matchedRoot
    ? overlays.find((overlay) => overlay.scope === matchedRoot.scope && overlay.targetRootPath === matchedRoot.path)
    : null;
  return byTargetRoot ?? overlays.find((overlay) => overlay.scope === "global") ?? overlays[0];
}

function renderAgentInstructionOverlay(workspaceModel: WorkspaceModel, label: string, scope: "global" | "notes" | "project", targetRootPath: string) {
  return [
    "# Exo Runtime Context",
    "",
    "Generated by Exo under `.exo/instructions/`. This file contains dynamic workspace facts for terminal agents. User-authored policy belongs in provider files such as `AGENTS.md`, `CLAUDE.md`, or other configured instruction files.",
    "",
    `- Overlay: ${label}`,
    `- Scope: ${scope}`,
    `- Target root: ${targetRootPath}`,
    `- Workspace root: ${workspaceModel.workspaceRoot}`,
    `- Default terminal cwd: ${workspaceModel.defaultTerminalCwd}`,
    "",
    "## Attached Notes Roots",
    "",
    ...listRootsForOverlay(workspaceModel.noteRoots),
    "",
    "## Attached Project Roots",
    "",
    ...listRootsForOverlay(workspaceModel.projectRoots),
    "",
    "## Exo Commands",
    "",
    "- `exo project-roots list` shows attached project roots.",
    "- Exo MCP search/read tools expose indexed notes context when enabled.",
    "- Keep project files out of notes indexing unless the user explicitly attaches them later.",
    "",
  ].join("\n");
}

function listRootsForOverlay(roots: Array<{ label: string; path: string }>) {
  return roots.length > 0
    ? roots.map((root) => `- ${root.label}: ${root.path}`)
    : ["- None attached."];
}

function overlayFileStem(label: string, rootPath: string) {
  const normalizedLabel = label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "root";
  return `${normalizedLabel}-${shortHash(rootPath)}`;
}

function shortHash(value: string) {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = ((hash << 5) - hash + value.charCodeAt(index)) | 0;
  }
  return Math.abs(hash).toString(36);
}

function isPathWithin(parentPath: string, candidatePath: string): boolean {
  const relative = path.relative(path.resolve(parentPath), path.resolve(candidatePath));
  return relative === "" || (!!relative && !relative.startsWith("..") && !path.isAbsolute(relative));
}
